### ISSUE TITLE
at-scripts（vcf to sweepfinder.py)

### ISSUE THREAD

**Issue by zhangleigloria** [arundurvasula/at-scripts#1]
Dear sir,
         I am sorry to bother you in your busy schedule. I want to ask you some questions. What is the requirement for the format of the input file(vcf file) when running this script? And When converting to the sweepfinder input file format, do all the scripts in in the "at-scripts" have to be used?Could you tell me about it?

best wishes

**Comment by arundurvasula** [comment]
Hi, 

this script is pretty brittle so I wouldn't recommend using it -- it expects haploid genotypes in the VCF and requires a fasta file mask. it expects the VCF to have multiple individuals and that genotypes be the only information for each individual (i.e. no information on genotype likelihoods or depth or other things that might be found in VCF files)

**Comment by zhangleigloria** [comment]
Thank you very much for your suggestions. I will find the better.

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Arun Durvasula"<notifications@github.com>;
 发送时间: 2019年5月14日(星期二) 凌晨4:25
 收件人: "arundurvasula/at-scripts"<at-scripts@noreply.github.com>;
 抄送: "张蕾"<1277375850@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [arundurvasula/at-scripts] at-scripts（vcf to sweepfinder.py) (#1)

 

 
Hi,
 
this script is pretty brittle so I wouldn't recommend using it -- it expects haploid genotypes in the VCF and requires a fasta file mask. it expects the VCF to have multiple individuals and that genotypes be the only information for each individual (i.e. no information on genotype likelihoods or depth or other things that might be found in VCF files)
